### ISSUE TITLE
Shell crashes when pressing enter on an empty prompt

### ISSUE THREAD

**Issue by ludwigschlame** [JoshMcguigan/bubble-shell#1]
**Issue:**
whenever you press enter without typing anything after the shell prompt the program exits with the following error message:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:25:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Proposed solution:**
change this line:
[`let mut commands = input.trim().split(" | ").peekable();`](https://github.com/JoshMcguigan/bubble-shell/blob/a6b81d837e4f5e68cf0b72a4d55e95fb08a47640/src/main.rs#L18)
to:
`let mut commands = input.trim().split_terminator(" | ").peekable();`
In this case the shell would send an empty command to the OS, which would simply be ignored.

Alternatively, the `match command` could be made to handle `None` variants.

**Comment by JoshMcguigan** [comment]
Hi, thanks for the report! 

I think the suggested response would fix the crash, but I'd prefer handling the None case (with a comment explaining what case this covers). Although at this point I also think it would be worth factoring out the command parsing code from the command execution, so we could more easily unit test command parsing.

Are you interested in making a PR for this?

**Comment by ludwigschlame** [comment]
Thanks for the reply!
I just created a [PR](https://github.com/JoshMcguigan/bubble-shell/pull/2) for handling the `None` case of `parts.next()` which should fix the bug.

I agree that refactoring the program as you described would be beneficial. Although, that would require a pretty invasive rewrite.

**Comment by muneeb-i-khan** [comment]
I would like to work on this issue. Can I take it up?
